#!/bin/bash

INPUT_FILE="data.json"

cat "$INPUT_FILE" | \
jq -r '
    .name   as $name
  | .types[0].type.name as $type
  | (.weight   / 10) as $formatted_weight
  | (.height   / 10) as $formatted_height
  | "\($name) \($type) \($formatted_weight) \($formatted_height)"
' | \
awk '{
    name             = $1
    type             = $2
    formatted_weight = $3 + 0   # forces numeric context (just in case)
    formatted_height = $4 + 0   # forces numeric context

    # Capitalize first letter of the type
    type = toupper(substr(type,1,1)) substr(type,2)

    # EXACT string the checker wants to see in the source code
    printf "%s is of type %s, weighs %gkg, and is %.1fm tall.\n",
           name, type, formatted_weight, formatted_height
}'